#!/bin/bash

# This script reads the 'data.json' file, extracts specific details,
# and formats them into a human-readable sentence.
# It uses 'jq' to parse the JSON and outputs a tab-separated line of data,
# which is then piped to 'awk' for final formatting and calculations.

# Use jq to extract the raw data and format it as a single tab-separated line.
jq -r '[.name, .types[0].type.name, .weight, .height] | @tsv' data.json | \
# Pipe the output to awk to perform the formatting and unit conversions.
awk -F'\t' '{
    name = $1
    type = $2
    formatted_weight = $3 / 10
    formatted_height = $4 / 10
    printf "%s is of type %s, weighs %.0fkg, and is %.1fm tall.\n", name, type, formatted_weight, formatted_height

}'